django/game_list/urls.py
from django.conf.urls import patterns, url
from game_list import views

urlpatterns = patterns(
    '',
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^status/$', views.status, name='status'),
    url(r'^download/$', views.download, name='download'),
    url(r'^games/$', views.games, name='games'),
    url(r'^retrieve_game/$', views.retrieve_game, name='retrieve_game'),
    url(r'^gadget/$', views.gadget, name='gadget'),
    url(r'^build_game/$', views.build_game, name='build_game'),
)

django/local_server/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^test/$', 'game_list.views.home'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^game/', include('game_list.urls', namespace='gamelist', app_name='game_list')),

)

django/game_list/models.py
from django.db import models

# Create your models here.

django/game_list/views.py
from django.shortcuts import render
from django.http import HttpResponse
import os
import random
import json
import bios

FILE_ROOT = os.path.normpath(os.path.dirname(os.path.realpath(__file__)))


def chunks(l, n):
    """ Yield successive n-sized chunks from l.
    """
    print(l)
    for i in range(0, len(l), n):
        yield l[i:i+n]


def home(request):

    context = {
        'project': 'Ludum Dare Team Bonanza',
    }

    return render(request, 'index.html', context)


def about(request):

    random.shuffle(bios.BIOS)
    context = {
        'project': 'Ludum Dare Team Bonanza',
        'bios': chunks(bios.BIOS, 3),
    }
    print(context['bios'])

    return render(request, 'about.html', context)


def status(request):
    context = {
        'project': 'Ludum Dare Team Bonanza',
    }

    return render(request, 'status.html', context)


def download(request):

    icons = random.sample(
        os.listdir(os.path.join(FILE_ROOT, 'static', 'img', 'os_icons')), 3)

    context = {
        'project': 'Ludum Dare Team Bonanza',
        'icon': icons
    }

    return render(request, 'download.html', context)

JSON = [
    {"game_number": -1, "game_name": "This is a game name!!", "players": "2/5", "status": "Particularly Slutty", "locked": True},
    {"game_number": -2, "game_name": "This is not a game name!!", "players": "5/5", "status": "Ummm... Good, I guess.", "locked": False},
    {"game_number": 53, "game_name": "Emily", "players": "1/3", "status": "Yeap", "locked": False},
    {"game_number": 54, "game_name": "Misty", "players": "2/3", "status": "Status Here", "locked": False},
    {"game_number": 55, "game_name": "Keelie", "players": "3/3", "status": "LKFJLDKF LKFJLkdflkdajfk", "locked": False},
    {"game_number": 57, "game_name": "Misty <3 Keelie 4 Evar", "players": "99/100", "status": "Hmmmmmmm", "locked": False},
    {"game_number": 59, "game_name": "Jacob <3 Emily", "players": "5/100", "status": "S'all good", "locked": True},
    {"game_number": 10, "game_name": "Max max max max max max", "players": "5/5", "status": "S'all good", "locked": True},
]


def games(request):
    # This should interact with individual game servers instead :)

    content = JSON
    print(request.POST)
    print(request.GET)
    print(request.method)
    print(request.body)
    game_number = request.POST['game_number']
    game_name = request.POST['game_name'].lower()
    players = request.POST['players'].lower()
    locked = request.POST['locked'].lower()
    print(game_number, game_name, players, locked)
    if game_number:
        game_number = int(game_number)
        for row in content:
            if int(row['game_number']) == game_number:
                content = [row]
                break

    rows = []
    if game_name:
        for row in content:
            if game_name in row['game_name'].lower():
                rows += [row]

        content = rows

    rows = []
    if players == 'hide full games':
        for row in content:
            n, m = row['players'].split('/')
            if n != m:
                rows += [row]

        content = rows

    rows = []
    if locked != 'all':
        for row in content:
            if locked == 'public' and not row['locked']:
                rows += [row]
            elif locked == 'private' and row['locked']:
                rows += [row]

        content = rows

    content = json.dumps({'gamedata': content})
    return HttpResponse(content, content_type='application/json')


def retrieve_game(request):
    print(request.POST)
    error = None
    if int(request.POST['game_number']) == -1:
        error = 'That is an invalid password!'
    content = json.dumps({
        'error': error,
        'connect_info': 'jacobvgardner.com/server/yep',
        })
    return HttpResponse(content, content_type='application/json')


def gadget(request):
    return render(request, 'gadget.xml')


def build_game(request):
    return HttpResponse('callback({"game_number": "8"})', content_type='application/json')

django/game_list/templates/about.html
{% extends "container.html" %}

{% block title %}About Us{% endblock %}

{% block nav-about %}
  <li class="active"><a href="#">
{% endblock %}

{% block content %}

	<style type="text/css">
		.about-left {
		}

		.about p {
			text-align: justify;
		}

		.about img {
			display: block;
			margin-left: auto;
			margin-right: auto;
		}

		.slider {
			display: none;
		}
		
		.collapseSlider{
			display: none;
		}
		.sliderExpanded .collapseSlider {
			display: block;
		}
		.sliderExpanded .expandSlider {
			display: none;
		}	

		.hand {
			color: #0000cc;
			cursor: hand;
			cursor: pointer;
		}
	</style>

	<div class="jumbotron">
		<h1>Who are we?!</h1>
		<p class="lead">
			Team Bonanza is an elite group of english majors, theatre majors, history majors, business majors, and psychology majors bringing you the very best in technology (oh there are a couple of engineers too).
		</p>
	</div>

	{% for chunk in bios %}
	<div class="row-fluid about">
		{% for bio in chunk %}
			<div class="span4">
				<img src="/static/about/{{ bio.img }}" class="img-circle img-polaroid" />
				<h2>{{ bio.name }}</h2>
				<h4>{{ bio.title }}</h4>
				<hr />
				<p>{{ bio.desc|safe }}</p>
			</div>
		{% endfor %}
	</div>
	{% endfor %}


<script type="text/javascript">
	function toggleSlides(){
		$('.toggler').click(function(e){
			var id=$(this).attr('id');
			var widgetId=id.substring(id.indexOf('-')+1,id.length);
			$('#'+widgetId).slideToggle();
			$(this).toggleClass('sliderExpanded');
			$('.closeSlider').click(function(){
					$(this).parent().hide('slow');
					var relatedToggler='toggler-'+$(this).parent().attr('id');
					$('#'+relatedToggler).removeClass('sliderExpanded');
			});
		});
	};
	$(function(){
		toggleSlides();
	});
</script>

{% endblock %}

django/game_list/templates/container.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{{ project }} :: {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Ludum Dare">
    <meta name="author" content="Jacob Gardner">

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 60px;
      }

      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1000px;
      }
      .container > hr {
        margin: 10px 0px;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 40px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 100px;
        line-height: 1;
      }
      .jumbotron .lead {
        font-size: 24px;
        line-height: 1.25;
      }
      .jumbotron .btn {
        font-size: 29px;
        padding: 14px 24px;
      }

      /* Customize the navbar links to be fill the entire space of the .navbar */
      .navbar .navbar-inner {
        padding: 0;
      }
      .navbar .nav {
        margin: 0;
        display: table;
        width: 100%;
      }
      .navbar .nav li {
        display: table-cell;
        width: 1%;
        float: none;
      }
      .navbar .nav li a {
        font-weight: bold;
        text-align: center;
        border-left: 1px solid rgba(255,255,255,.75);
        border-right: 1px solid rgba(0,0,0,.1);
      }
      .navbar .nav li:first-child a {
        border-left: 0;
        border-radius: 3px 0 0 3px;
      }
      .navbar .nav li:last-child a {
        border-right: 0;
        border-radius: 0 3px 3px 0;
      }

      .table td {
         text-align: center;     
      }

      .table th {
         text-align: center;   
      }
    </style>

    <link rel="shortcut icon" href="/static/favicon.ico">
  </head>

  <body>
    <div class="container">
      <div class="masthead" id="main-container">
        <h3 class="muted">{{ project }}</h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                {% block nav-list %}<li><a href="{% url 'gamelist:home' %}">{% endblock %}<i class="icon-list-alt"></i> Server List</a></li>
                {% block nav-download %}<li><a href="{% url 'gamelist:download' %}">{% endblock %}<i class="icon-download"></i> Download</a></li>
                {% block nav-status %}<li><a href="{% url 'gamelist:status' %}">{% endblock %}<i class="icon-beaker"></i> Server Status</a></li>
                {% block nav-about %}<li><a href="{% url 'gamelist:about' %}">{% endblock %}<i class="icon-group"></i> About</a></li>
                
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>
      
      <script src="/static/js/jquery-1.9.1.min.js"></script>
      <script src="/static/js/jquery.client.js"></script>
      <script src="/static/js/bootstrap.min.js"></script>

      {% block content %}Looks like the developers forgot to extend this.  IDIOTS{% endblock %}

      <hr>

      <div class="footer">
        <p>&copy; {{ project }} 2013</p>
      </div>
    </div> <!-- /container -->

    <a href="https://github.com/jacobgardner/ludum-dare-support"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_green_007200.png" alt="Fork me on GitHub"></a>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40057205-1', 'jacobvgardner.com');
      ga('send', 'pageview');

    </script>
  </body>
</html>

django/game_list/templates/download.html
{% extends "container.html" %}

{% block title %}Download{% endblock %}

{% block nav-download %}
  <li class="active"><a href="#">
{% endblock %}

{% block content %}
<div class="jumbotron">
<h1>Download <i class="icon-download"></i></h1>
<p class="lead">
Here's where you'll find downloads
</p>
</div>

<div class="row-fluid">
  <div style="text-align: center;" class="span4">
    <h2>Windows</h2>
    <img src="/static/img/os_icons/{{ icon.0 }}" class="img-rounded">
    <p><a id="windows" class="btn btn-info" href="#">
    Download 4 Windows</a></p>
  </div>
  <div style="text-align: center;" class="span4">
    <h2>Linux</h2>
    <img src="/static/img/os_icons/{{ icon.1 }}" class="img-rounded">
    <p><a id="linux" class="btn btn-info" href="#">Download 4 Linux</a></p>
 </div>
  <div style="text-align: center;" class="span4">
    <h2>Macintosh</h2>
    <img src="/static/img/os_icons/{{ icon.2 }}" class="img-rounded">
    <p><a id="mac" class="btn btn-info" href="#">Download 4 Macintosh</a></p>
  </div>
</div>

<p class='pull-right'><small>Plush icons courtesy of <a href="http://iconsmaster.com">iconsmaster.com</a>.</small>

<script>
$(document).ready(function() {
  btn = $('#' + $.client.os.toLowerCase());

  if( btn.length != 0 ) {
    btn.removeClass('btn-info');
    btn.addClass('btn-success');
  }
});
</script>

{% endblock %}

django/game_list/templates/index.html
{% extends "container.html" %}

{% block title %}Server List{% endblock %}

{% block nav-list %}
  <li class="active"><a href="#">
{% endblock %}


{% block content %}
<!-- Jumbotron -->
<div class="jumbotron">
<h1>Quick Connect <i class="icon-bolt"></i></h1>
<p class="lead">Press the comically large button below to be automatically joined to a game.</p>
<a class="btn btn-large btn-success" href="#">Quick Connect!</a><br/><br/>
<div class="alert alert-block alert-error">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Use at your own risk!</h4>
  We do not guarantee that the server you connect to will have intelligent, polite, clothed, or sentient players.   
  </div>

<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>

</div>

<hr />

<div class="jumbotron" style="margin: 5px">

<a href="https://plus.google.com/hangouts/_?gid=916338472305" id="create-game-hangout" class="btn btn-primary" rel="tooltip" data-title="Create a game where all participates will be in a Google+ Hangout Together" target="_blank">
	<img src="https://ssl.gstatic.com/images/icons/gplus-32.png">
	Create Game With Hangout
</a>

<button id="create-game-no-hangout" type="button" class="btn btn-primary" rel="tooltip" data-title="Create a game without using a Google+ hangout">
	Create Game Without Hangout 
	<img src="/static/img/sad_face.png">
</button>
</div>
<hr />

<buttton id="refresh-btn" type="button" class="btn btn-inverse" rel="tooltip" data-title="Refresh the game list below">Refresh List</buttton>
<!-- Example row of columns -->
<div class="row-fluid">
	<table id='gametable' class='table table-striped table-bordered'>
		<thead>
			<tr>
				<th class="span2" style="padding: 2px;">
					<input 
						id="game-number" type="text" class="span12" placeholder="Game #" style="margin: 0px;" 
						rel="tooltip" data-title="Search For A Specific Game Number" />
				</th>
				<th class="span5" style="padding: 2px;">
					<input 
						id="game-name" type="text" class="span12" placeholder="Game Name" style="margin: 0px;" 
						rel="tooltip" data-title="Filter Games By Name" />
				</th>
				<th class="span2" style="padding: 2px;">
					<select 
						id="player-filter" style="margin: 0px;" 
						rel="tooltip" data-title="Filter Out Full Games">
							<option>Players</option>
							<option>Hide Full Games</option>
					</select>
				</th>
				<th class="span4">
					<a href="#" rel="tooltip" data-title="Game Features - What Features Are In This Game">Features</a>
				</th>
				<th class="span3" style="padding: 2px;">
					<div 
						id="lock-filter" class="btn-group" data-toggle="buttons-radio"
						rel="tooltip" data-title="Filter Out Public/Private Games">
							<button type="button" class="btn active">All</button>
							<button type="button" class="btn">Private</button>
							<button type="button" class="btn">Public</button>
					</div>
				</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>

<style type="text/css">
	.table {
		position: relative;
		background: #ffffff;
		z-index: 2;
	}

	#sync {
		position: fixed;
		top: -40px;
		left: 50%;
		height: 40px;
		width: 500px;
		margin-left: -250px;
	}

	.alerts {
		z-index: 2000;
		position: fixed;
		width: 100%;
		left: 0;
		bottom: 0px;
		margin: 0px;
	}

	.alert {
		margin: 0;
	}

	.new-alert {
		left: -100%;
		position: relative;
	}

	#refresh-btn {
		position: relative;
		left: 50%;
		width: 150px;
		margin-left: -75px;
		margin-bottom: -3px;
		z-index: 1;
	}	

</style>


<div class="alerts" id="alerts">
<span id="alert-header"></span>
</div>

<button id="sync" type="button" class="btn btn-info"><i class="icon-refresh icon-spin"></i> Syncronizing Content...</button>


<span id="dialogs">

<div id="password-dialog" class="modal fade hide" tabindex="-1" role="dialog" aria-labelledby="wutIsThis" aria-hidden="true">
	<div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">Please Enter The Game Password...</h3> </div>
	<form id="password-form form-inline" style="margin-bottom: 0px">
		<div class="modal-body" style="padding-bottom: 0px">
			<input id="pass" type="password" class="input-small span4" placeholder="You Put The Password Here" />
	  	</div>
	  	<div class="modal-footer">
	    	<button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
	    	<button type="submit" id="doit" class="btn btn-primary">Do it</button>
	  	</div>
  	</form>
</div>
</span>

<script type="text/javascript" src="/static/js/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/static/js/prj/notifications.js"></script>
<script type="text/javascript" src="/static/js/prj/connect.js"></script>
<script type="text/javascript" src="/static/js/prj/game_list.js"></script>
<script type="text/javascript" src="/static/js/prj/sockets.js"></script>
<script type="text/javascript" src="/static/js/prj/create_game.js"></script>

<script type="text/javascript">
	$('[rel=tooltip]').tooltip();

	$('#create-game-no-hangout').click(create_game);

	var player_filter = 'All';
	var lock_filter = 'All';
	var selected_game = null;
	var websockets_enabled = true;

	// These values are needed by other scripts.  They are configured here :)
	var game_url = '{% url 'gamelist:retrieve_game' %}';
	var csrf_token = '{{ csrf_token }}';
	var download_page = '{% url 'gamelist:download' %}';
	var server_list = '{% url 'gamelist:games' %}';

	function set_csrf(xhr, settings) {

     	if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
            // Only send the token to relative URLs i.e. locally.
            xhr.setRequestHeader("X-CSRFToken", csrf_token);
     	}
	}

	$('#password-form').submit(function() {
		if(selected_game) {
			get_game(selected_game, $('#pass').val());
			$("#password-dialog").modal('hide');
		}
		return false;
	});

	$('#refresh-btn').click(load_list);

	// Filters Cause Server List Updates
	$('#player-filter').change(function() {
		player_filter = $('#player-filter').val();
		load_list();
	});

	$('#lock-filter > button.btn').on('click', function() {
		lock_filter = this.innerHTML;
		load_list();
	});

	var filter_timeout = 0;
	$('#game-number').keyup(function() {
		clearTimeout(filter_timeout);
		filter_timeout = setTimeout(load_list, 500);
	});
	$('#game-name').keyup(function() {
		clearTimeout(filter_timeout);
		filter_timeout = setTimeout(load_list, 500);
	});

	// Sync Bar
	function start_load(xhr, settings)
	{
		set_csrf(xhr, settings);	

		$('#sync').stop();

		$('#sync').animate({
			top: '-5px'
		}, 100);
	}

	function end_load()
	{
		$('#sync').stop();

		$('#sync').animate({
			top: '-40px'
		});
	}

	$(document).ready(function() {
		if( typeof(WebSocket) != 'function' ) {
			websockets_enabled = false; // :(
		}

		load_list();

		if( websockets_enabled == true ) {
			attempt_connection();
		}
	});

</script>

{% endblock %}

django/game_list/templates/status.html
{% extends "container.html" %}

{% block title %}Server Status{% endblock %}

{% block nav-status %}
  <li class="active"><a href="#">
{% endblock %}

{% block content %}

<div class="jumbotron">
<h1>Server Status!</h1>
<p class="lead">
Well, because you can read this, the django server is doing well.  I should talk to the game server to see if he's doing ok... well... maybe not...
</p>
</div>
{% endblock %}